ftrackhq/integrations

- apps/connect/source/ftrack_connect/plugin_manager/__init__.py
- apps/connect/source/ftrack_connect/plugin_manager/plugin_list.py
- apps/connect/source/ftrack_connect/plugin_manager/processor.py
- apps/connect/source/ftrack_connect/util.py
…drop of platform dependent plugins
Resolves : 
* CLICKUP-
* FT-8c389c6a-c28c-494c-9349-0be13d858a04
* SENTRY-
* ZENDESK-
- Support drag-n-drop of platform dependent plugins
- Fixed multithreading issue in plugin manager refresh
Do a full ETE test on plugin manager.
> fix: Fix plugin manager

- libs/qt/source/ftrack_qt/widgets/lists/asset_list.py
Resolves : 
* CLICKUP-
* FT-437062bb-4141-4a02-acbd-a65da77f75d1
* SENTRY-
* ZENDESK-
Pre select the latest published asset on open an publish.
> feat: pre select latest published asset

- libs/framework-core/source/ftrack_framework_core/engine/__init__.py
Resolves : 
* CLICKUP-
* FT-71df35c6-0dd2-4f8e-8c89-a30876cec318
* SENTRY-
* ZENDESK-
Remove store from mixpanel events
> fix: remove store from run plugin when sending mix panel event

- apps/connect/pyproject.toml
- apps/connect/source/ftrack_connect/__init__.py
- apps/connect/source/ftrack_connect/plugin_manager/welcome.py
- apps/connect/source/ftrack_connect/util.py
Resolves : 
* CLICKUP-
* FT-5f3c23ba-01bb-4d5c-b732-ab10583040b9
* SENTRY-
* ZENDESK-
- Use requests instead of PyGithub to fetch releases from Github.
- Fixed bug in PM welcome dialog plugin install.
Do a full PM test.
> feat: Backlog/replace pygithub

- apps/connect/source/ftrack_connect/__init__.py
- apps/connect/source/ftrack_connect/util.py
- projects/connect-publisher-widget/pyproject.toml
- projects/connect-timetracker-widget/connect-plugin/hook/time_tracker_widget.py
- projects/connect-timetracker-widget/pyproject.toml
- tools/build.py
Resolves : 
* CLICKUP-
* FT-e0209055-757a-4fe9-845c-e592236355de
* SENTRY-
* ZENDESK-
- Remove connect from Connect plugin build filename
- Allow up to Python 3.11 for publisher and timetracker widget
- Fixed missing import in timetracker widget hook
Build and test publisher and timetracker.
> feat: Remove connect from Connect plugin build filename

- apps/connect/source/ftrack_connect/plugin_manager/__init__.py
- apps/connect/source/ftrack_connect/plugin_manager/plugin_list.py
- apps/connect/source/ftrack_connect/plugin_manager/welcome.py
- apps/connect/source/ftrack_connect/util.py
Resolves : 
* CLICKUP-
* FT-0bcd5140-d584-4da2-8754-30bdf7d6a3c0
* SENTRY-
* ZENDESK-
Removed plugin install logic from welcome dialog, instead properly call plugin processor
Test all edge cases of plugin installation scenarios
> feat: Consolidate plugin manager welcome dialog logic

- .github/workflows/build-library.yml
- libs/framework-widget/release_notes.md
- libs/utils/pyproject.toml
Resolves : 
* CLICKUP-
* FT-75cc82e9-217c-40a4-abca-0ded45024e03
* SENTRY-
* ZENDESK-
If tag is pushed for a library it automatically builds and publish to pypi.
> feat: Backlog/build libs on tag

- libs/utils/release_notes.md
- libs/utils/source/ftrack_utils/paths/__init__.py
Resolves : 
* CLICKUP-
* FT-aace4104-514b-4fd5-9d0d-a61c374c9e28
* SENTRY-
* ZENDESK-
Have utils get_temp_path take on extension with or without leading .
> feat: Have utils get_temp_path take on extension with or without .

- apps/connect/source/ftrack_connect/__init__.py
- apps/connect/source/ftrack_connect/ui/application.py
- apps/connect/source/ftrack_connect/ui/widget/about.py
- apps/connect/source/ftrack_connect/util.py
- installers/connect-installer/doc/conf.py
- installers/connect-installer/docker/C7.Dockerfile
- installers/connect-installer/docker/C8.Dockerfile
- installers/connect-installer/docker/README.rst
- installers/connect-installer/docker/Win10.Dockerfile
- installers/connect-installer/resource/hook/ftrack_connect_installer_version_information.py
- installers/connect-installer/setup.py
- installers/connect-installer/source/ftrack_connect_installer/__init__.py
- installers/connect-installer/source/ftrack_connect_installer/__main__.py
Resolves : 
* CLICKUP-
* FT-
* SENTRY-
* ZENDESK-
- Fix ftrack plugin path in connect installer
- Fix about dialog Connect version
- Fixed bug in about dialog were not all plugin debug informations were considered
- Allowed RV integration versioning in plugin bootstrap (YY.mmp)
Build installer and install Connect, test about dialog
> fix: Backlog/fix ftrack plugin path in connect installer

- installers/connect-installer/resource/Info.plist
- installers/connect-installer/setup.py
Resolves : 
* CLICKUP-
* FT-
* SENTRY-
* ZENDESK-
- Github releases does not support whitespace in artifact filenames, updated Connect installer setup.py to accomodate this.
- Fixed wrong tar folder name on Linux.
Test building Connect installer, verify that artifact filenames starts with "ftrack-Connect" and Linux decompress to "ftrack-connect"
> fix: Fix Connect installer deployment filenames

- libs/framework-core/release_notes.md
- libs/framework-core/source/ftrack_framework_core/exceptions/plugin.py
- projects/framework-common-extensions/tool-configs/standalone-file-opener.yaml
Resolves : 
* CLICKUP-
* FT-
* SENTRY-
* ZENDESK-
libs/framework-core:
- [fix] PluginValidationError; Have on_fix_callback as an optional argument
This solves issue in common extensions were PluginValidationError is called clean without the "on_fix_callback" argument, can be reproduced in for example PS when opening a file that does not exist anymore.
> fix: PluginValidationError; Have on_fix_callback as an optional argument

- projects/framework-photoshop/extensions/plugins/photoshop_document_collector.py
- projects/framework-photoshop/release_notes.md
Resolves : 
* CLICKUP-
* FT-
* SENTRY-
* ZENDESK-
Fixed bug when publishing an unsaved document causing an exception in collector
> fix: Fixed bug when publishing an unsaved document causing an exception in collector

- libs/qt/release_notes.md
- libs/qt/source/ftrack_qt/widgets/selectors/asset_selector.py
Resolves : 
* CLICKUP-
* FT-a61efbfa-36bc-4e4f-b9d8-795e671f535b
* SENTRY-
* ZENDESK-
[fix] asset_selector; Fix resize bug
> fix: Fix scaling on width on publisher

- projects/framework-photoshop/extensions/plugins/photoshop_document_saved_validator.py
- projects/framework-photoshop/extensions/plugins/photoshop_save_to_temp_finalizer.py
- projects/framework-photoshop/release_notes.md
Resolves : 
* CLICKUP-
* FT-
* SENTRY-
* ZENDESK-
Fixed path bug on Windows saving .psb files
> fix: Fixed path bug on Windows saving .psb files

- projects/framework-nuke/extensions/plugins/nuke_nodegraph_image_exporter.py
Resolves : 
* CLICKUP-
* FT-17ac1c87-4fe8-4723-880f-6db74ecfcb04
* SENTRY-
* ZENDESK-
Fixed a regression with Nuke nodegraph image exporter
> fix: nuke nodegraph image exporter regression

- libs/qt/source/ftrack_qt/widgets/lists/asset_list.py
- projects/framework-common-extensions/release_notes.md
Resolves : 
* CLICKUP-
* FT-
* SENTRY-
* ZENDESK-
- Disabled auto scrolling on asset list. 
- Always select the first item on activation.
> fix: Disabled auto scrolling on asset list. Always select the first item on activation.

- libs/qt/release_notes.md
- libs/qt/source/ftrack_qt/widgets/frames/new_asset_input.py
- libs/qt/source/ftrack_qt/widgets/selectors/asset_selector.py
- projects/framework-common-extensions/release_notes.md
Resolves : 
* CLICKUP-
* FT-
* SENTRY-
* ZENDESK-
libs/qt
[fixed] Fixed bug in asset_selector, if no assets on startup - properly emit asset name changed signal.
> fix: Fixed bug in asset_selector, if no assets on startup - properly emit asset name changed signal

- libs/framework-qt/pyproject.toml
- libs/framework-qt/release_notes.md
- tools/build.py
Resolves : 
* CLICKUP-
* FT-
* SENTRY-
* ZENDESK-
Fixed bug in build script cause non platform independenct connect pluin ZIP:s to get OS filename suffix
> fix: Fixed bug in build script cause non platform independenct connect pluin ZIP:s to get OS filename suffix

- projects/framework-nuke/extensions/plugins/nuke_nodegraph_image_exporter.py
- projects/framework-nuke/extensions/plugins/nuke_save_to_temp_finalizer.py
- projects/framework-nuke/extensions/plugins/nuke_script_exporter.py
- projects/framework-nuke/extensions/plugins/nuke_script_saved_validator.py
Resolves : 
* CLICKUP-
* FT-824cd33d-aa78-4a53-8721-f55dc0e9cf87
* SENTRY-
* ZENDESK-
fix: Align extensions to not contain dot
> fix: Align extensions to not contain dot

- projects/framework-nuke/source/ftrack_framework_nuke/__init__.py
- projects/framework-nuke/source/ftrack_framework_nuke/utils/__init__.py
Resolves : 
* CLICKUP-
* FT-2fc0468e-08c4-4b53-8d05-8320e627d8a6
* SENTRY-
* ZENDESK-
Run dialog callback in Nuke main thread
> feat: Run dialog callback in Nuke main thread

- libs/qt/source/ftrack_qt/widgets/asset/new_asset_input_widget.py
- libs/qt/source/ftrack_qt/widgets/lists/asset_list.py
- tests/framework/manual/standalone_ui_test.py
Resolves : 
* CLICKUP-
* FT-
* SENTRY-
* ZENDESK-
Propagate mouse press event properly
> fix: Propagate mouse press event properly

- apps/connect/release_notes.md
- apps/connect/source/ftrack_connect/plugin_manager/plugin_list.py
Resolves : 
* CLICKUP-
* FT-edaa83bf-7134-4723-8f62-3b81c520f054
* SENTRY-
* ZENDESK-
[changed] Plugin manager; Drag-n-drop of a plugin ZIP overrides any existing plugins in plugin list
Test plugin manager
> feat: Drag-n-dropped plugins prioritized in plugin list

- apps/connect/release_notes.md
- apps/connect/source/ftrack_connect/plugin_manager/__init__.py
- apps/connect/source/ftrack_connect/plugin_manager/plugin_list.py
- apps/connect/source/ftrack_connect/utils/plugin.py
Resolves : 
* CLICKUP-
* FT-75b8644b-c80b-4f3e-b4aa-946ce03e1a35
* SENTRY-
* ZENDESK-
* [new] Toggle pre-releases in Plugin manager
> feat: Connect plugin manager filter on pre-releases

- apps/connect/release_notes.md
- apps/connect/source/ftrack_connect/utils/plugin.py
Resolves : 
* CLICKUP-
* FT-
* SENTRY-
* ZENDESK-
Properly sort releases fetched from Github - the previous implementation relied on releases being reported back in correct order from Github.
> fix: Optimized and properly using version parsing when sorting Github releases.

- projects/framework-nuke/extensions/plugins/nuke_node_collector.py
- projects/framework-nuke/extensions/plugins/nuke_writeable_node_validator.py
- projects/framework-nuke/extensions/tool-configs/nuke-script-publisher.yaml
- projects/framework-nuke/release_notes.md
… reviewable to be created.[changed] When selecting the node to render for reviewable, show all nodes with the selected one on top.
Resolves : 
* CLICKUP-
* FT-bb89fdd3-b703-4c70-8a1a-6d0001f98182
* SENTRY-
* ZENDESK-
* [changed] When selecting the node to render for reviewable, show all nodes with the selected one on top.
* [new] Writeable node validator, to check if a node is writeable for a reviewable to be created.
> fix: Writeable node validator, show all nodes in node selector - not only selected, for user choice

- tools/cookiecutter-framework-project/{{cookiecutter.project_name}}/connect-plugin/__version__.py
- tools/cookiecutter-framework-project/{{cookiecutter.project_name}}/connect-plugin/hook/discover_ftrack_framework_{{cookiecutter.integration_name}}.py
- tools/cookiecutter-framework-project/{{cookiecutter.project_name}}/extensions/launch/{{ cookiecutter.integration_name }}-launch.yaml
- tools/cookiecutter-framework-project/{{cookiecutter.project_name}}/extensions/plugins/{{ cookiecutter.integration_name }}_save_to_temp_finalizer.py
- tools/cookiecutter-framework-project/{{cookiecutter.project_name}}/extensions/plugins/{{ cookiecutter.integration_name }}_scene_collector.py
- tools/cookiecutter-framework-project/{{cookiecutter.project_name}}/extensions/plugins/{{ cookiecutter.integration_name }}_scene_exporter.py
- tools/cookiecutter-framework-project/{{cookiecutter.project_name}}/extensions/plugins/{{ cookiecutter.integration_name }}_scene_opener.py
- tools/cookiecutter-framework-project/{{cookiecutter.project_name}}/extensions/requirements.txt
- tools/cookiecutter-framework-project/{{cookiecutter.project_name}}/extensions/{{ cookiecutter.integration_name }}.yaml
- tools/cookiecutter-framework-project/{{cookiecutter.project_name}}/pyproject.toml
- tools/cookiecutter-framework-project/{{cookiecutter.project_name}}/resource/bootstrap/init.py
- tools/cookiecutter-framework-project/{{cookiecutter.project_name}}/source/{{ cookiecutter.package_name }}/__init__.py
- tools/cookiecutter-framework-project/{{cookiecutter.project_name}}/source/{{ cookiecutter.package_name }}/utils/__init__.py
Resolves : 
* CLICKUP-
* FT-
* SENTRY-
* ZENDESK-
> fix: Align cookiecutter template with latest framework changes

- libs/qt/source/ftrack_qt/widgets/buttons/options_button.py
Resolves : 
* CLICKUP-
* FT-
* SENTRY-
* ZENDESK-
- Fix bug on options button, that should make PySide6 stable
> fix: Backlog/fix options button py side6

- tools/cookiecutter-framework-project/{{cookiecutter.project_name}}/README.md
- tools/cookiecutter-framework-project/{{cookiecutter.project_name}}/connect-plugin/__version__.py
- tools/cookiecutter-framework-project/{{cookiecutter.project_name}}/pyproject.toml
- tools/cookiecutter-framework-project/{{cookiecutter.project_name}}/source/{{ cookiecutter.package_name }}/__init__.py
- tools/cookiecutter-framework-project/{{cookiecutter.project_name}}/source/{{ cookiecutter.package_name }}/utils/__init__.py
… Fix init get dcc version; Fixed dock_<dcc>right util; Fixed util missing wraps import
Resolves : 
* CLICKUP-
* FT-
* SENTRY-
* ZENDESK-
- Remove doc build from README and toml
- Restructured toml ftrack deps
- Fix init get dcc version
- Fixed dock_<dcc>right util
- Fixed util missing wraps import
- Removed connect-plugin/__version__.py
> fix: Fix cookiecutter from Houdini and Unreal bugs found

- .github/workflows/build-connect.yml
- installers/connect-installer/setup.py
Resolves : 
* CLICKUP-
* FT-
* SENTRY-
* ZENDESK-
connect ci/cd
- Update CI to use intel mac instead of new default M1
> fix: Update CI to use intel mac instead of new default M1

- projects/framework-nuke/extensions/launch/nuke-launch.yaml
- projects/framework-nuke/extensions/launch/nukex-launch.yaml
- projects/framework-nuke/release_notes.md
Resolves : 
* CLICKUP-
* FT-
* SENTRY-
* ZENDESK-
framework-nuke
- Nuke launcher; Properly escaped version expressions
> fix: Nuke launcher; Properly escaped version expressions.

- libs/framework-core/pyproject.toml
- libs/framework-core/release_notes.md
- libs/framework-core/source/ftrack_framework_core/registry/__init__.py
Resolves : 
* CLICKUP-
* FT-
* SENTRY-
* ZENDESK-
_framework-core:_
- [fix] Registry; Prevent crash if no extensions.
> fix: Core::Registry; Prevent crash if no extensions.

- tools/cookiecutter-framework-project/{{cookiecutter.project_name}}/extensions/plugins/{{ cookiecutter.integration_name }}_save_to_temp_finalizer.py
- tools/cookiecutter-framework-project/{{cookiecutter.project_name}}/extensions/plugins/{{ cookiecutter.integration_name }}_scene_collector.py
- tools/cookiecutter-framework-project/{{cookiecutter.project_name}}/extensions/plugins/{{ cookiecutter.integration_name }}_scene_exporter.py
- tools/cookiecutter-framework-project/{{cookiecutter.project_name}}/extensions/plugins/{{ cookiecutter.integration_name }}_scene_opener.py
- tools/cookiecutter-framework-project/{{cookiecutter.project_name}}/extensions/plugins/{{ cookiecutter.integration_name }}_scene_saved_validator.py
- tools/cookiecutter-framework-project/{{cookiecutter.project_name}}/extensions/plugins/{{ cookiecutter.integration_name }}_thumbnail_exporter.py
Resolves : 
* CLICKUP-
* FT-
* SENTRY-
* ZENDESK-
cookiecutter-framework:
- Make cookiecutter plugins runnable OOTB
> fix: Make cookiecutter plugins runnable OOTB

- apps/connect/release_notes.md
- apps/connect/source/ftrack_connect/application_launcher/__init__.py
Resolves : 
* CLICKUP-
* FT-
* SENTRY-
* ZENDESK-
_apps/connect:_
- [changed] Prevent additional icon for standalone process to appear on windows.
Launch PS, not extra icon should appear in taskbar.
> feat: Surpress standalone icon on windows

- apps/connect/release_notes.md
- apps/connect/source/ftrack_connect/__init__.py
- apps/connect/source/ftrack_connect/plugin_manager/plugin_list.py
- apps/connect/source/ftrack_connect/utils/plugin.py
Resolves : 
* CLICKUP-
* FT-
* SENTRY-
* ZENDESK-
_apps/connect:_
- [new] Ability to set the default URL for downloading releases from Github in the plugin manager, by setting the environment variable FTRACK_CONNECT_GITHUB_RELEASES_URL. Also supports disabling fetch by setting it to 'none'.
> feat: Set or disable Github releases URL 

- libs/qt/release_notes.md
- libs/qt/source/ftrack_qt/utils/threading/__init__.py
…
Resolves : 
* CLICKUP-
* FT-
* SENTRY-
* ZENDESK-
_libs/qt:_
- [fix] Fix invoke_in_qt_main_thread so it properly returns the result of the function
> fix: Fix invoke_in_qt_main_thread so it properly returns the result of the function

- projects/framework-common-extensions/dialogs/standard_loader_dialog.py
- projects/framework-common-extensions/dialogs/standard_opener_dialog.py
- projects/framework-common-extensions/dialogs/standard_publisher_dialog.py
- projects/framework-common-extensions/release_notes.md
Resolves : 
* CLICKUP-
* FT-
* SENTRY-
* ZENDESK-
framework-common-extensions:
* [fixed] Fix bug were dialog creation crashed if not tool configs. Also disabled run button.
> fix: Backlog/fix dialog bug if no tool config

- projects/framework-nuke/extensions/nuke.yaml
- projects/framework-nuke/extensions/plugins/nuke_image_loader.py
Resolves : 
* CLICKUP-
* FT-
* SENTRY-
* ZENDESK-
Added missing Nuke movie and sequence loaders
> fix: Add missing Nuke loaders

- tools/cookiecutter-framework-project/{{cookiecutter.project_name}}/extensions/plugins/{{ cookiecutter.integration_name }}_scene_opener.py
Remove .capitalize method from plugin name in cookiecutter template.
> fix: Remove .capitalize() from plugin name

- .github/workflows/build-connect.yml
- .github/workflows/build-library.yml
- .github/workflows/build-plugin.yml
- .github/workflows/push-main-test.yml
Resolves FT-b87fed5c-05ad-466e-bed5-a18cbf0515cf
- set upload/download artifact action version to 4 as 2 is deprecated and probably broke the CI
- set hidden file flag to allow for .coverage because of new breaking changes introduced by the action team
- is the CI passing?
> chore: Update upload/download action version to 4

- README.md
Windows users might use the package manager scoop to install python on their system. pre-commit is not able to detect the correct python installation in that case.
Users will have to apply the scoop provided registry modification. This commit adds this information to the readme.
Resolves : 
* FT-cef61e51-33cc-4aeb-8313-58e47e8262e0
- [x ] Windows.
> fix: Add hint for windows users using scoop

- apps/connect/release_notes.md
- apps/connect/source/ftrack_connect/__main__.py
Launching ftrack-connect fails on windows if setuptools is not installed globally or in the virtualenv. This is due to the pkg_resources import.
The import has been introduced 10 years ago via this commit: https://github.com/ftrackhq/integrations/commit/89f206dfdd31ae6d5994a7560d93da369ddd70c4
All usages have since been removed.
Resolves : 
* CLICKUP-
* FT-140bf5fb-0b06-44fc-8ec2-5d61026580ac
* SENTRY-
* ZENDESK-
- [ x] Windows.
> fix: Removes obsolete pkg_resources import

- apps/connect/release_notes.md
- apps/connect/source/ftrack_connect/__main__.py
Implements ctrl+c interrupt handling improvement
The prior method was not working on windows. Windows is not
creating a SIGINT signal from its console applications when
presseng ctrl+c. This new method works on all systems by
utilizing Qts internal signal handlers.
Resolves : 
* FT-ca59e6c3-8351-4067-bc52-cef6af407910
> fix: Backlog/handle ctrl c interrupt on windows

- apps/connect/release_notes.md
- apps/connect/source/ftrack_connect/__main__.py
Move PySide2 specific HighDPI options
This moves PySide2 specific HighDPI options into a PySide2
specific codepath. This will get rid of Deprecation warnings
within the PySide6 codepath. These options are not exposed
anymore in PySide6 as they are enabled by default and not
intended for turning them off.
Resolves : 
* CLICKUP-
* FT-0d89065a-8218-4b68-98e3-2278789550ca
* SENTRY-
* ZENDESK-
> fix: Backlog/move pyside2 specific flag

- libs/qt/source/ftrack_qt/utils/widget/__init__.py
- libs/utils/pyproject.toml
- libs/utils/release_notes.md
Resolves : 
* CLICKUP-
* FT-311b6500-a53f-4708-83ba-78cefe6a61b9
* SENTRY-
* ZENDESK-
**Purpose:** 
When querying the tags based on the options in the progres widget, there was a bug converting the string values to a list.
**Scope:** 
**Approach:** 
**Changes:** 
> fix: rolling back str changes

- libs/framework-core/pyproject.toml
- libs/framework-core/release_notes.md
- libs/framework-core/source/ftrack_framework_core/host/__init__.py
Resolves : 
* CLICKUP-
* FT-95a424a9-fc6f-48c0-88c1-221e1e65e77a
* SENTRY-
* ZENDESK-
**Purpose:** 
Make sure we always create a new session when running tool configs on host. So we can avoid corrupted sessions.
**Scope:** 
**Approach:** 
**Changes:** 
> fix:Add new session decorator back

- libs/qt/pyproject.toml
- libs/qt/release_notes.md
- libs/utils/pyproject.toml
- libs/utils/release_notes.md
Resolves : 
* CLICKUP-
* FT-
* SENTRY-
* ZENDESK-
**Purpose:** 
Fix mistake releasing utils when we should have been releasing qt.
**Scope:** 
**Approach:** 
**Changes:** 
> fix: Roll back release notes on utils and add release notes and release qt

- projects/framework-maya/extensions/plugins/maya_playblast_exporter.py
- projects/framework-maya/poetry.lock
- projects/framework-maya/pyproject.toml
- projects/framework-maya/release_notes.md
- projects/framework-maya/source/ftrack_framework_maya/utils/__init__.py
Resolves : 
* CLICKUP-
* FT-
* SENTRY-
* ZENDESK-
**Purpose:** 
Maya 2025 has fully migrated to PySide6 and Qt5. We had a file where we where loading shiboken2 by mistake, that is fixed. Also now playblast has the override flag set to True by default as it nows complains when the temp file already exists.
**Scope:** 
**Approach:** 
**Changes:** 
> fix: fix maya 2025 shiboken2 error and playblast, also update version to RC

- libs/utils/release_notes.md
- libs/utils/source/ftrack_utils/usage/track_usage.py
Resolves : 
* CLICKUP-
* FT-7ec0e3f3-cb47-4908-aba6-4b50e7953136
* SENTRY-
* ZENDESK-
**Purpose:** 
Change the usage tracker log error of not having an existing instance to debug.
**Scope:** 
**Approach:** 
**Changes:** 
> fix: set loger level of non usage tracker to debug insteaad of error

- projects/framework-blender/extensions/plugins/blender_object_mode_validator.py
- projects/framework-blender/extensions/plugins/blender_playblast_exporter.py
- projects/framework-blender/extensions/plugins/blender_scene_exporter.py
- projects/framework-blender/extensions/plugins/blender_thumbnail_exporter.py
- projects/framework-blender/extensions/tool-configs/blender-scene-publisher.yaml
Playblasts will now be generated with the correctly selected camera.
Selection exports now work when objects are in edit mode. There's a new validator that includes a fix to set the objects to OBJECT mode.
> fix: selection export and playblast creation

- .github/workflows/build-connect.yml
- .github/workflows/build-plugin.yml
Resolves : 
* CLICKUP-
* FT-
* SENTRY-
* ZENDESK-
**Purpose:** 
Macos12 runner is deprecated. Updated to 13.
**Scope:** 
**Approach:** 
**Changes:** 
> fix: update macos12 to macos13 on the runner actions. 12 is deprecated.
