ftrackhq/integrations

README.md
Resolves : 
* CLICKUP-
* FT-d361895c-3c0d-4da1-b04f-d140c9bfb9fc
* SENTRY-
* ZENDESK-
Update readme file. Remove deprecated information.
=> fix: readme file updated

apps/connect/doc/release/release_notes.rst, apps/connect/source/ftrack_connect/hook/open_component_directory.py
port https://github.com/ftrackhq/ftrack-connect/pull/9/files to new monorepo
=> feat: port host for actions from previous repo

README.md
Resolves : 
* CLICKUP-
* FT-29da2b7e-6ef0-4a28-938a-87c41609dc15
* SENTRY-
* ZENDESK-
Add temporal documentation to readme file and update python versions
=> feat: update python version and add banner with temp doc

apps/connect/release_notes.md, installers/connect-installer/release_notes.md, libs/constants/release_notes.md, libs/framework-core/release_notes.md, libs/framework-qt/release_notes.md, libs/framework-widget/release_notes.md, libs/qt-style/release_notes.md, libs/qt/release_notes.md, libs/utils/release_notes.md, projects/connect-publisher-widget/release_notes.md, projects/connect-timetracker-widget/release_notes.md, projects/framework-common-extensions/release_notes.md, projects/framework-maya/release_notes.md, projects/framework-nuke/release_notes.md, projects/framework-photoshop-js/release_notes.md, projects/framework-photoshop/release_notes.md, projects/nuke-studio/release_notes.md, projects/rv/release_notes.md, tools/build.py, tools/cookiecutter-framework-project/release_notes.md
Resolves : 
* CLICKUP-
* FT-c5956701-cce5-47df-a3c6-c33cf207952c
* SENTRY-
* ZENDESK-
Added release notes to all packages
Ported/converted existing release notes.
=> feat: Initial release notes

libs/constants/pyproject.toml, libs/framework-widget/release_notes.md
Resolves : 
* CLICKUP-
* FT-
* SENTRY-
* ZENDESK-
=> feat: Backlog/update rc on constants

apps/connect/pyproject.toml, libs/constants/pyproject.toml, libs/framework-core/pyproject.toml, libs/framework-qt/pyproject.toml, libs/framework-widget/release_notes.md, libs/qt-style/pyproject.toml, libs/qt/pyproject.toml, libs/utils/pyproject.toml, projects/connect-publisher-widget/pyproject.toml, projects/connect-timetracker-widget/pyproject.toml, projects/framework-maya/pyproject.toml, projects/framework-nuke/pyproject.toml, projects/framework-photoshop/pyproject.toml, projects/nuke-studio/pyproject.toml, projects/rv/pyproject.toml
Resolves : 
* CLICKUP-
* FT-da0a94d5-d3e0-49b7-8596-5b3f4b27c371
* SENTRY-
* ZENDESK-
Make sure RC versions are allowed to be picked meanwhile we do the tests.
=> feat: Backlog/update framework versions

.github/workflows/build-release.yml, libs/framework-widget/release_notes.md, projects/connect-publisher-widget/connect-plugin/__version__.py, projects/connect-timetracker-widget/connect-plugin/__version__.py, tools/build.py
Resolves : 
* CLICKUP-
* FT-8f8cce4d-3912-4d07-b4a8-b10f75514728
* SENTRY-
* ZENDESK-
=> fix: Backlog/make sure install poetry 1.5.1

libs/framework-core/pyproject.toml
Resolves : 
* CLICKUP-
* FT-
* SENTRY-
* ZENDESK-
=> fix: Backlog/cleanup

installers/connect-installer/README.md, installers/connect-installer/setup.py
Resolves : 
* CLICKUP-
* FT-8dac261a-2966-43b1-879a-3386573eb4b6
* SENTRY-
* ZENDESK-
Have Connect installer Linux build setup.py to prodce tarball and md5
=> feat: Improved Connect Linux build, align MacOS, create md5 

projects/framework-photoshop/poetry.lock, projects/framework-photoshop/pyproject.toml, projects/framework-photoshop/release_notes.md
Resolves : 
* CLICKUP-
* FT-
* SENTRY-
* ZENDESK-
=> feat: PS release

projects/nuke-studio/extensions/launch/nuke-studio-launch.yaml
Resolves : 
* CLICKUP-
* FT-
* SENTRY-
* ZENDESK-
=> fix: Align NKS launcher

projects/framework-nuke/extensions/tool-configs/nuke-script-publisher.yaml
Resolves : 
* CLICKUP-
* FT-486b4f87-9943-4c4c-85f8-6a62b8fc03fd
* SENTRY-
* ZENDESK-
Validate all exported paths in Nuke
=> feat: Validate all exported paths in Nuke 

apps/connect/poetry.lock, apps/connect/pyproject.toml, apps/connect/release_notes.md, installers/connect-installer/release_notes.md, installers/connect-installer/requirements.txt, installers/connect-installer/setup.py
Resolves : 
* CLICKUP-
* FT-
* SENTRY-
* ZENDESK-
=> feat: Prerelease/connect 24.3.0rc1

projects/framework-common-extensions/release_notes.md, projects/framework-common-extensions/widgets/asset_version_selector.py, projects/framework-common-extensions/widgets/publisher_asset_version_selector.py, tests/framework/manual/standalone_ui_test.py
Resolves : 
* CLICKUP-
* FT-a7cf52d4-dba0-41c2-9ddb-66e8da83c5c7
* SENTRY-
* ZENDESK-
Asset version selectors; show label on empty asset list.
=> feat: Asset version selectors; show label on empty asset list.

projects/framework-nuke/pyproject.toml
Resolves : 
* CLICKUP-
* FT-
* SENTRY-
* ZENDESK-
=> fix: Update Nuke pyproject toml

projects/framework-photoshop/pyproject.toml, projects/framework-photoshop/release_notes.md, projects/framework-photoshop/source/ftrack_framework_photoshop/rpc_cep.py, projects/framework-photoshop/source/ftrack_framework_photoshop/utils/process.py
Resolves : 
* CLICKUP-
* FT-
* SENTRY-
* ZENDESK-
[fix] Prevent re-occurring TASKLIST popup on Windows.
=> fix: Prevent re-occurring TASKLIST popup on Windows. Improve logging on RPC timeout

projects/framework-nuke/pyproject.toml, projects/framework-nuke/release_notes.md
Resolves : 
* CLICKUP-
* FT-
* SENTRY-
* ZENDESK-
Release patch framework-nuke/v24.4.1
=> feat: Backlog/release framework nuke v24.4.1

apps/connect/pyproject.toml, apps/connect/release_notes.md, installers/app-installer/release_notes.md, installers/app-installer/source/ftrack_app_installer/__init__.py
Resolves : 
* CLICKUP-
* FT-
* SENTRY-
* ZENDESK-
_app-installer:_
- fix codesign exe windows
=> fix: Backlog/fix codesign exe windows

libs/qt/pyproject.toml, libs/qt/release_notes.md, libs/qt/source/ftrack_qt/utils/widget/__init__.py
Resolves : 
* CLICKUP-
* FT-
* SENTRY-
* ZENDESK-
libs/qt:
- [fix] Backlog/qt fix shiboken2
=> fix: Backlog/qt fix shiboken2

apps/connect/pyproject.toml, apps/connect/release_notes.md, apps/connect/source/ftrack_connect/__init__.py, apps/connect/source/ftrack_connect/ui/login_tools.py, installers/app-installer/source/ftrack_app_installer/__init__.py
Resolves : 
* CLICKUP-
* FT-
* SENTRY-
* ZENDESK-
_apps/connect:_
- [fix] Fix issue with connect login not working on Windows.
Test logging out and login again, should work as expected.
=> fix: Backlog/fix connect login windows

tools/build.py
Resolves : 
* CLICKUP-
* FT-
* SENTRY-
* ZENDESK-
_tool/build.py_
- feat: CEP build; Support for JS include folder, overriding extensions/js folder.
=> feat: CEP build; Support for JS include folder, overriding extensions/js folder.

libs/utils/release_notes.md, libs/utils/source/ftrack_utils/rpc/js_rpc.py
Resolves : 
* CLICKUP-
* FT-
* SENTRY-
* ZENDESK-
libs/utils:
- [feat] Aligned on_run_dialog_callback with DCC bootstrap implementation.
To be tested with PS and Premiere bootstrap PR.
=> feat: Aligned on_run_dialog_callback with DCC bootstrap implementation.

libs/framework-core/release_notes.md, libs/framework-core/source/ftrack_framework_core/registry/__init__.py, libs/framework-core/source/ftrack_framework_core/widget/dialog.py, libs/utils/release_notes.md, libs/utils/source/ftrack_utils/extensions/overrides.py, libs/utils/source/ftrack_utils/extensions/registry.py
Resolves : 
* CLICKUP-
* FT-
* SENTRY-
* ZENDESK-
_utils & framework-core_
- [new] Registry; Support for JS extensions, extension type "js_functions"
Testable with the Toonboom Harmony integration
=> feat: Registry; Support for JS extensions

libs/framework-qt/release_notes.md, libs/framework-qt/source/ftrack_framework_qt/dialogs/base_dialog.py, projects/framework-maya/extensions/plugins/maya_scene_loader.py
Resolves : 
* CLICKUP-
* FT-
* SENTRY-
* ZENDESK-
=> fix: Backlog/event blocker on base dialog

libs/framework-core/source/ftrack_framework_core/widget/dialog.py, libs/framework-qt/release_notes.md, libs/framework-qt/source/ftrack_framework_qt/dialogs/base_dialog.py, projects/framework-common-extensions/dialogs/standard_loader_dialog.py, projects/framework-maya/extensions/maya.yaml, projects/framework-maya/extensions/plugins/maya_scene_loader.py, projects/framework-maya/extensions/tool-configs/maya-scene-loader.yaml, projects/framework-maya/extensions/widgets/maya_scene_load_selector.py, projects/framework-maya/release_notes.md
Resolves : 
* CLICKUP-
* FT-
* SENTRY-
* ZENDESK-
=> feat: Backlog/framework maya loader

projects/framework-maya/extensions/plugins/maya_scene_exporter.py, projects/framework-maya/extensions/widgets/maya_scene_options_selector.py, projects/framework-maya/pyproject.toml, projects/framework-maya/release_notes.md
Resolves : 
* CLICKUP-
* FT-
* SENTRY-
* ZENDESK-
**Purpose:** 
There where errors in the publisher when publishing just the selection and with .ma as extension type.
**Scope:** 
**Approach:** 
**Changes:** 
=> fix: Backlog/maya fix export type

libs/utils/pyproject.toml, libs/utils/release_notes.md
Resolves : 
* CLICKUP-
* FT-
* SENTRY-
* ZENDESK-
**Purpose:** 
**Scope:** 
**Approach:** 
**Changes:** 
=> feat: update version of utils

libs/framework-core/pyproject.toml, libs/framework-core/release_notes.md, libs/framework-core/source/ftrack_framework_core/configure_logging.py, libs/framework-core/source/ftrack_framework_core/log/__init__.py
Resolves : 
* CLICKUP-
* FT-
* SENTRY-
* ZENDESK-
**Purpose:** 
**Scope:** 
**Approach:** 
**Changes:** 
=> fix: changed the log save file level from warning to info

.github/workflows/build-plugin.yml, projects/framework-max/extensions/plugins/max_save_to_temp_finalizer.py, projects/framework-max/pyproject.toml
Resolves : 
* CLICKUP-
* FT-
* SENTRY-
* ZENDESK-
**Purpose:** 
**Scope:** 
**Approach:** 
**Changes:** 
=> fix: Backlog/fix max release

projects/framework-blender/pyproject.toml, projects/framework-blender/release_notes.md
Resolves : 
* CLICKUP-
* FT-
* SENTRY-
* ZENDESK-
**Purpose:** 
**Scope:** 
**Approach:** 
**Changes:** 
=> fix: update blender version

.github/workflows/push-main-test.yml, projects/rv/README.md, projects/rv/connect-plugin/hook/ftrack_rv_launcher.py, projects/rv/release_notes.md, tools/build.py
Update build system to include dependencies.zip
Review launchers to ensure are showing up as expected
Lock ubuntu images for test suite.
=> fix: Update RV and build system

apps/connect/source/ftrack_connect/ui/widget/data_drop_zone.py
improve padding detection as suggested by ticket #278758
=> fix: improve clique sequence padding detection on publisher
